### ISSUE TITLE
Compilation Errors in dctl with Latest bit_set, tabula, and xstd using MSVC

### ISSUE THREAD

**Issue by NEIL-smtg** [rhalbersma/dctl#34]
Hi, I work on Microsoft Visual C++ testing, where we regularly build popular open-source projects, including dctl, with development builds of our compiler and libraries.

Recently, I attempted to build dctl from source with MSVC using the latest commits of bit_set, tabula, and xstd. However, I encountered several compilation errors, including:
```c++
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(21,35): error C2993: 'int': is not a valid type for non-type template parameter 'N'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(21,35): note: the template instantiation context (the oldest one first) is
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(18,7): note: while compiling class template 'dctl::core::basic_mask'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(46,33): error C3203: 'array': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(49,89): error C2109: subscript requires array or pointer type
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(37,37): error C3312: no callable 'begin' function found for type 'const dctl::core::basic_mask<dctl::core::block_adl::basic_board<dctl::core::block_adl::international>>::set_type'
...
```

I suspect these errors stem from changes introduced in https://github.com/rhalbersma/bit_set/commit/bb19573740a1aaea92b283f6d9113a86d1637ef0. Would it be possible to update dctl’s source code to accommodate these changes? Let me know if you need additional details regarding the errors.

Here is the full build log:
[dctl.log](https://github.com/user-attachments/files/19578916/dctl.log)

**Comment by ebrancati** [comment]
same issue with GCC 14

**Comment by PhoebeHui** [comment]
Same issue with msvc build(VS2022) when build the latest souce.
