### ISSUE TITLE
DCTL build fails on MSVC with error C2280, error C2088, error C3889...

### ISSUE THREAD

**Issue by shizhuoer** [rhalbersma/dctl#32]
Hi all,
DCTL failed to build with "error C2280, error C2088, error C3889..."with MSVC on Windows. Could you please help look at this issue?

**Environment:**
Windows: windows server 2019
VS: 2019

**Repro steps:**
1.open VS2019 x64 tools command
2.git clone https://github.com/rhalbersma/dctl F:\gitP\rhalbersma\dctl
3.cd F:\gitP\rhalbersma\dctl
4.mkdir build_amd64 & cd F:\gitP\rhalbersma\dctl\build_amd64
5.set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
6.msbuild /m /p:Platform=x64 /p:Configuration=Release dctl.sln /t:Rebuild

**Error info:**
F:\gitP\rhalbersma\dctl\include\dctl/core/model/detail/builder.hpp(221,86): error C2280: 'bool dctl::core::basic_action<dctl::core::block_adl::international,dctl::core::block_adl::basic_board<dctl::core::block_adl::international>>::operator ==(const dctl::core::basic_action<dctl::core::block_adl::international,dctl::core::block_adl::basic_board<dctl::core::block_adl::international>> &) const': attempting to reference a deleted function [F:\gitP\rhalbersma\dctl\build_amd64\example\play.vcxproj]
F:\gitP\rhalbersma\dctl\include\dctl/core/model/detail/builder.hpp(221,86): error C2088: '==': illegal for class [F:\gitP\rhalbersma\dctl\build_amd64\example\play.vcxproj]
F:\gitP\rhalbersma\dctl\include\dctl/core/model/detail/builder.hpp(221,37): error C3889: call to object of class type 'std::ranges::_None_of_fn': no matching call operator found [F:\gitP\rhalbersma\dctl\build_amd64\example\play.vcxproj]
F:\gitP\rhalbersma\dctl\include\dctl/core/model/detail/builder.hpp(204,55): error C2297: '||': not valid as right operand has type 'void' [F:\gitP\rhalbersma\dctl\build_amd64\example\play.vcxproj]
F:\tools\boost_1_70_0\x64\boost/graph/topological_sort.hpp(44,1): error C2220: the following warning is treated as an error [F:\gitP\rhalbersma\dctl\build_amd64\test\egdb.divide.vcxproj]

**log**
[build.log](https://github.com/rhalbersma/dctl/files/9744711/build.log)

**Comment by joemmett** [comment]
It looks like this was fixed in `xstd`, the project will now compile with MSVC version 17.4.4.

**Comment by rhalbersma** [comment]
I have no access to MSVC at the moment, builds cleanly with gcc 15. Feel free to reopen if MSVC doesn't build.
